### ISSUE TITLE
Stick with BitcoinAverage.com?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#120]
Is the reference client going to stick with BitcoinAverage.com for rates? What is the plan and roadmap for bitcoin-to-fiat exchange rates?

(I ask because the specific rates used *greatly* affect the OpenBazaar payment service I am building, called Duo Money.)

**Comment by cpacia** [comment]
it's going to need to be changed to the same formula josh is using in the UI.

**Comment by JustinDrake** [comment]
Pinging @jjeffryes to agree on an exchange rate spec.

**Comment by JustinDrake** [comment]
Pinging @jjeffryes and @drwasho to discuss exchange rates.

**Comment by jjeffryes** [comment]
In the client we use:
https://blockchain.info/ticker
https://api.coinkite.com/public/rates
https://api.bitcoinaverage.com/all
http://api.bitcoincharts.com/v1/weighted_prices.json

The results are averaged, which is necessary both for greater accuracy and because at any time one or more of them may fail and not return data.

**Comment by drwasho** [comment]
@cpacia can we close this issue? Is the server calculating the average in the same way as the client?

**Comment by jjeffryes** [comment]
I think the server is only using 1 service instead of 4.

**Comment by JustinDrake** [comment]
It's unclear to me how the client and server come to consensus (if at all) on the price.

**Comment by drwasho** [comment]
This is an old issue addressed by #285
