### ISSUE TITLE
OpenBazaar folder appears in my home folder (OSX).

### ISSUE THREAD

**Issue by DanielMurrell** [OpenBazaar/OpenBazaar-Server#163]
Isn't the standard way to do this to make a .openbazaar folder in the home folder so that it's invisible?

**Comment by hoffmabc** [comment]
I don't think we're trying to hide it. If so there would be better places for that.

**Comment by JustinDrake** [comment]
@hoffmabc: It's rather unusual for Mac apps to clobber `~` with data.

**Comment by hoffmabc** [comment]
we can just move it to "/Users/username/Library/Application Support". Not a big deal.

**Comment by JustinDrake** [comment]
Sounds good

**Comment by bdunbar** [comment]
Is this actually a problem?  Putting the OpenBazaar directory in $home/OpenBazaar across all supported platforms seems like a good idea, not a bad one.

**Comment by hoffmabc** [comment]
Well it's not a huge problem, but on OS X that's generally a pretty accessible folder and one used for dumping shit into rather than the Application Support folder which is much more hidden and protected from inadvertent crap.

**Comment by bdunbar** [comment]
Duly noted, thanks.

**Comment by DanielMurrell** [comment]
Yeah, it's just a minor thing that might annoy some people. Moving it to /Users/username/Library/Application Support would be good, no-one looks there.

**Comment by BazaarBay** [comment]
Why not AppData as all other applications do?

**Comment by tcharding** [comment]
I wholly agree. Creating OpenBazaar in home 'folder' is not playing nice. It would be more respectful to users if the default behavior was platform specific i.e for OS X it should be in the place OSX users expect it (not commenting since I am not OS X). On the Linux platform it should be in a dot directory in the home directory and all in lowercase, for example .openbazaar. I have a pull request ready that refactors constants.py (where this behaviour is implemented), I added a function to partly implement this platform specific behavior already but left it inactive (using defaults) so as to not change the current behaviour. If there is a consensus (from the OpenBazaar devs) perhaps it would be ok if I put in a pull request with the new behaviour?

**Comment by tcharding** [comment]
This issue is fixed currently in master branch. It is not activated though. Can be activated with the following patch:

diff --git a/config.py b/config.py
index 906467d..658135c 100644
--- a/config.py
+++ b/config.py
@@ -23,7 +23,7 @@ for i in range(2):
 
 DEFAULTS = {
     # Default project config file may now remove these items
-    'data_folder': 'OpenBazaar',  # FIXME change to 'None' when issue #163 is resolved
+    'data_folder': None,
     'ksize': '20',
     'alpha': '3',
     'transaction_fee': '10000',
