### ISSUE TITLE
Revisiting Tor Compatibility

### ISSUE THREAD

**Issue by ABISprotocol** [OpenBazaar/OpenBazaar-Server#164]
To kick off this discussion please see (from previous comments in deprecated repository) the following:
https://github.com/OpenBazaar/OpenBazaar/issues/866#issuecomment-103611744

@El--Presidente @meZee @dionyziz @sophron @hoffmabc 

Please add your thoughts on how Tor or I2P could be made integrated & working with OB (the current version).

**Comment by ac225519** [comment]
Anonymizing the user has no priority.
This means you have to use a good VPN (see the VPN reviews of TorrentFreak) if you insist on anonymous use for now.

**Comment by ABISprotocol** [comment]
I don't assume here that VPN use equates to anonymity - far from it.  I do know that Tor and I2P both have specific purposes, and pros and cons.  I argued against the Tor use with OB for awhile in the (deprecated) version because of the significant problems that were evident at that time with use of Tor and bitcoin (including problems created by low-resource attackers).   At a later date, after the issues had been explored more thoroughly, I asked if there could be a possibility to  implement "TCP in addition to UDP as an optional connection type which would allow Tor to work properly," or other ideas relating to Tor or I2P.  Though there is no set priority for these kinds of ideas to be implemented here, I am opening this issue for discussion so that there might be more examination of the details surrounding them in the context of OB with the hopes that eventually there may be some possibility of Tor or I2P working with OB.

**Comment by cpacia** [comment]
So one of the problems with having Tor only nodes is it can prevent the dht from functioning properly. There is redundancy built in, but if a large number of nodes are unreachable for incoming connections by non-Tor nodes then the dht queries can break down. 

Having a separate Tor-only or i2p only network could work but combining them seems like it could be problematic. 

Also, if we later on decide to scrap our DHT in favor of ipfs, then maybe we could revisit doing it all in one network.

**Comment by ABISprotocol** [comment]
what are the pros and cons of having the DHT vs. the ipfs (in a nutshell) in this context?

**Comment by ABISprotocol** [comment]
@cpacia Rephrased, what are pros and cons of the existing system that OB has vs. IPFS?

Also, would it be feasible to incorporate [something like this](https://github.com/Ayms/node-Tor) where peers implement a Kademlia DHT and websocket bridges are a Peersm bridge?  Supposedly in this latter case, "Each peer is implementing the Tor protocol (Onion proxy and Onion router) and the ORDB function."

In that above case mentioned it is Tor only, but as you mentioned IPFS could potentially accomodate the use of Tor and I2P.

**Comment by ac225519** [comment]
@ABISprotocol please take the time and read though the white paper of both projects.
https://privatelee.com/search/?q=IPFS+whitepaper
https://privatelee.com/search/?q=OpenBazaar+whitepaper
Don't ask [homework questions](http://www.catb.org/esr/faqs/smart-questions.html#homework)

**Comment by ABISprotocol** [comment]
I will decline to respond to the condescending remark above.  The questions I have posed for @cpacia are to generate discussion and to invite further ideas.

**Comment by cpacia** [comment]
Well with IPFS we could do something like post  a mutable (but signed) object containing our listings using IPNS and other people could download that (potentially from multiple nodes) to get a list of our listings. Then each listing could put in added to IPFS so that everytime someone downloads the listing they become a seeder of that listing so that anyone else can download it. 

It adds redundancy to hosting your listings and makes it somewhat more distributed. We could do the same thing natively in our code, but it seems kind of pointless to spend a lot of effort to do what another team is working on exclusively. 

The question would be whether or not to keep our own DHT around if we use IPFS. There are some things we use ours for that IPFS can't do (or at least I don't think it can) but they way we do it currently isn't great and we will probably need to find something better eventually. So we could maybe scrap our DHT entirely in the future. 

I think we just need to wait and see how IPFS works when it's production ready.

**Comment by drwasho** [comment]
Link to #240

**Comment by ABISprotocol** [comment]
Thank you!

**Comment by Austin-Williams** [comment]
Network segregation is pretty much a given in my estimation. I suspect that's more of a feature than a bug. I don't have a lot of confidence in a node's ability to remain anonymous if they interact simultaneously on both networks. I suspect correlation attacks could be performed by cheaply in such a case.

Switching back and forth should be optional and easy for the user (ie: they shouldn't have to download a second client) -- albeit with a clear indication to the user that they are OpSec concerns that arise if they constantly switch back and forth.

All else being equal, I would prefer a Tor approach to an I2P approach due to the significant testing, funding, and academic research put into Tor.

**Comment by SamPatt** [comment]
>All else being equal, I would prefer a Tor approach to an I2P approach due to the significant testing, funding, and academic research put into Tor.

I tend to agree, I think the discussion around I2P is largely because the network design is more compatible (UDP instead of TCP).

**Comment by drwasho** [comment]
Update: since we're going to be moving to IPFS for the backend, this issue will become about integrating OpenBazaar with however IPFS works with Tor. Still a little ways down the road at the present time.

**Comment by drwasho** [comment]
Issue closed and merged into #362
