### ISSUE TITLE
Search in Discover does not always return results

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#179]
The following requests were sent to the server, items that have these tags show up in the Discover view, but the search requests return no results. 

{"request":{"api":"v1","id":"z76acdeqd81wnrk9","command":"search","keyword":"retro"}}
{"request":{"api":"v1","id":"emvu48i8f8b8olxr","command":"search","keyword":"vintage"}}

This request, on the other hand, does return results

{"request":{"api":"v1","id":"xc8mna4y11tw3ik9","command":"search","keyword":"test"}}

**Comment by cpacia** [comment]
It's hard to know what the problem is. I think those keywords aren't in the dht for some reason. Either they expired and we're removed. Or somehow the original store request didn't propagate right.

I'm going to add republish functionality soon. Maybe once every 24 hours or so. I think that will take care of that. Unless there are bigger dht issues I don't know about.

**Comment by drwasho** [comment]
Is this still a problem @jjeffryes ?
