### ISSUE TITLE
Cannot start "import stun" error

### ISSUE THREAD

**Issue by bitcoinbrisbane** [OpenBazaar/OpenBazaar-Server#204]
On Ubuntu server, after following the README, I get this error.  Am I missing a dependency or something?

ubuntu@arm:~/OpenBazaar-Server$ python openbazaard.py start --testnet
Traceback (most recent call last):
  File "openbazaard.py", line 7, in <module>
    import stun
ImportError: No module named stun

**Comment by bitcoinbrisbane** [comment]
Fixed it pip install pystun

**Comment by horsecoin** [comment]
I had this error too because I was using python 3 instead of the required python 2
what I did to correctly get the dependencies was:
python2.7 -m pip install -r requirements.txt
python openbazaard.py start -a [your.ip.here]

![screen shot 2016-04-06 at 9 47 41 pm](https://cloud.githubusercontent.com/assets/6550459/14344102/525b1d9c-fc41-11e5-93b6-30bbae979b30.png)
