### ISSUE TITLE
Add HTTPS to resolver.onename.com

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#233]
TLS is available so let's not forget to update the code.

**Comment by shea256** [comment]
Also, I'd note that different resolver implementations are going to have different URL formats. One may be formatted like this:

```
https://resolver.onename.com/v2/users/{name}
```

Another may be formatted like this:

```
https://resolver.blockstack.org/v1/lookup?name={name}&timeout=2
```

Thus, I'd have the default resolver format be set to this:

```
https://resolver.onename.com/v2/users/{name}
```

Then you can just do a string replacement on `{name}`.

And any new resolver URL that a user puts in will have to have a valid domain and include `{name}` somewhere in the URL.

**Comment by shea256** [comment]
Also, one of my usernames has an underscore in it and it's not getting accepted.

**Comment by hoffmabc** [comment]
What are all the valid characters for a Blockchain ID?

**Comment by shea256** [comment]
The short answer: alphanumerics and underscores.

The long answer:

The nearly universal standard for username characters is alphanumerics and underscores (Facebook decided to ignore this and allow dashes instead of underscores). The standard for domain names is alphanumerics and dashes.

Since the Blockstack server supports the registration of both usernames and domains, the superset of these sets is allowed (alphanumeric, underscores and dashes).

That said, with usernames / Blockchain IDs, only alphanumerics and underscores are allowed.

**Comment by muneeb-ali** [comment]
Also, right now the endpoint assumes that you're interested in the .id namespace. Very soon there are going to be other TLDs/namespaces. We'll keep the above endpoint live for backwards compatibility but will probably have another endpoint e.g., lookup, that lets you resolve names on any TLD. (keeping /users/ in the URL made sense when we were only concerned with users in the .id namespace).

**Comment by shea256** [comment]
:+1:

**Comment by hoffmabc** [comment]
@cpacia can we leave this open until we

**Comment by shea256** [comment]
Until we... Until we?!

**Comment by hoffmabc** [comment]
Hah I didn't realize i submitted that.
