### ISSUE TITLE
I2P Natively Supported

### ISSUE THREAD

**Issue by mandamu5** [OpenBazaar/OpenBazaar-Server#240]
Brief Description: Support for I2P natively

Operating System (OS and version): Linux / Windows / OS X / *nix
OpenBazaar version: -current

Due to the limitations of Tor, and its (let's be honest) being a haven of malfeasance, the alternative of I2P (which robustly supports UDP and addresses DHT limitations by design -- one of its intended use cases to support pseudonymous Bittorrent clients) should be explored. 

More than a cursory glance at I2P will reveal a small but significant skilled and motivated base of programmers in the I2P community who have provided many working implementations of software (as a thread on the Subreddit at /I2P/ mentioned recently, on the topic of OpenBazaar, that I2P devs have themselves built many working implementations of software like Zeronet, Bittorrent, Vuze, et cetera. The common thread, for all, has been that the I2P development community is so niche that these programs often become stale and lose development interest because the end up as a "proof of concept" and the initial project creators don't put forth any substantial efforts to supporting the community.

For those concerned about exposing their IP addresses, and simply having a rather MINIMAL expectation of some privacy, have you thought about supporting I2P? I understand the mantra "just use a VPN," but VPNs fail open, thus revealing the user's IP adress, without her taking great strides to ensure they close their internet connection if the VPN connection hiccups. 

Moreover, many would prefer to run OpenBazaar-Server on their own hardware as opposed to trusting a VPS to manage it. This is just obviously overhead for many who want (such as myself, and I _KNOW_ others) a rather straightforward use case to do three things simultaneously:
(i) provide my own resources to the OB community (not those from a "cloud provider" or a VPS)
(ii) Not risk exposing my IP address to the world
(iii) Be treated as the LAW-ABIDING merchant that I am

OpenBazaar is not, by design, a good fit for Tor. I2P solves all the problems inherent to the OB design and I think that by OB supporting it natively, the problem that's been seen in other projects where I2P developers have had to take the reigns out of the gates, it's been shown that support wanes and then just dies as the native projects themselves continue unabated. Please show some regard for those who don't want their IP exposed to the world and value their privacy to do so.

**Comment by cpacia** [comment]
I would be OK with using I2P though I have very little experience with it. I'd welcome contributions from people who know what they're doing in that regard.

**Comment by drwasho** [comment]
Would definitely welcome and consider PRs that would integrate I2P into OpenBazaar.

**Comment by noflag** [comment]
I2P doesn't use outproxies, so the network would have to be separate. That might actually be safer in the long run. Just have a "private browsing" switch in the client.

**Comment by hoffmabc** [comment]
Yes both i2p and Tor would be separate networks. A hybrid approach would not work.

**Comment by papermate** [comment]
I was working in this days on outproxying the OB connection through I2P. 
It is not that easy, at least for me, while the communication between client and server pass without too many troubles through I2P tunnels.

The change could be made without too much of an effort if using onioncat on top of it, so that instead of a b32 (the basic identity used in I2P) you may have a ipv6 to identify the node, which of course would not be the real one.
The seeder and all the rest of the network must be on the network overlay too to use this solution.

I don't see any reason not to set it as default and only network. Right now OB does not protect the less tech-savy, and is forcing anyone to buy a VPN or looking for other means of protection by design, which adds a layer of complexity for the end user.
I2P not only protects the identity but also adds layers of encryption to the communication. If you think SSL/TLS is good, this is better.

A couple of weeks of delay in the project looks like a good tradeoff for really coming out with a full working, protected and "battery included" software.
Separating the users from the start in more subnetwork seems to me like a godd way to kill the usability of OB

If I can be of some help in testing or anything please let me know, I'm not a programmer but I'd be glad to help.

**Comment by hoffmabc** [comment]
If not already can you please visit the Slack so we can discuss this further in more detail.

**Comment by papermate** [comment]
I joined the slack and:
- Slackbot keeps disagreeing with Pidgin on IRC saying I didn't give him a password. I'll side with Pidgin though, password is there. It succeded in making me lose 40 minutes looking for problems though.
- Been in Welcome-room since 3 hours and well, no answers about anything
- It uses a huge mass of client side scripts, it managed to freak out my browser again and again
- Why not here?
- Why closed source/proprietary?

**Comment by str4d** [comment]
Hi! I'm one of the developers of I2P. I agree with the OP that having something like OpenBazaar get I2P support would be really neat! I'm posting here so you know I am happy to answer questions :)

I haven't yet grepped the source and don't know anything about how your existing backend works, but in case it is useful, there are currently two Python libraries for I2P (both backed by the [SAMv3](https://geti2p.net/en/docs/api/samv3) API):

- [`txi2p`](https://github.com/str4d/txi2p): provides Twisted endpoints (only supports TCP because that is all Twisted supports).
- [`i2p.socket`](https://github.com/majestrate/i2p.socket): a drop-in replacement for the regular `socket` that adds `AF_I2P` for trivial I2P support.

**Comment by cpacia** [comment]
The txi2p looks interesting. Doesn't look too difficult to use.

**Comment by ABISprotocol** [comment]
Technical question, I'm assuming this is a "just I2P" approach, but if someone was running I2P with Foxyproxy, [like this](https://lilithlela.cyberguerrilla.org/?p=5794), this would work also to connect?

**Comment by papermate** [comment]
What use case do you mean?
Like, you are on OB and someone else is on the I2P network you want OB to opportunistically switch to a I2P connection?
In that case I think the best solution would be to integrate in the client interface a PAC, so you don't need any plugin or stuff. Still, the best solution would be to integrate everything into I2P, so let's hope it will not be needed ;)

**Comment by drwasho** [comment]
Issue closed and merged into #362
