### ISSUE TITLE
Missing currency: Moldovan Leu

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar-Server#250]
OpenBazaar version: 0.1.0
Hardware: PC

Reproducible: Always

Steps to reproduce:
1. Install OpenBazaar
2. On step 4 there is no Moldovan Leu

Additional info (links, images, etc go here):

This currency actually exists :) https://www.google.com/#q=moldovan+leu

![screenshot from 2016-03-02 10 39 20](https://cloud.githubusercontent.com/assets/1475489/13455703/a855636a-e067-11e5-816b-5d5856161dbc.png)

**Comment by viorels** [comment]
OpenBazaar-Client is getting the currencies and exchange rates from a couple of places: blockchain.info, coinkite, bitcoinaverage, bitcoincharts. None of these list the rate for MDL.

My first thought was to add LocalBitcoins as a source, but looks like there is not enough volume for MDL there either: https://localbitcoins.com/bitcoincharts/MDL/trades.json
So I assume that's why they don't list it in their API at https://localbitcoins.com/bitcoinaverage/ticker-all-currencies/

So the next question is, where do you exchange MDL for BTC so we could get the price from there?

**Comment by moldcraft** [comment]
> blockchain.info, coinkite, bitcoinaverage, bitcoincharts. None of these list the rate for MDL

&nbsp;

> there is not enough volume for MDL 

Ok, Thanks.
