### ISSUE TITLE
Add caching headers to REST API calls 

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#279]
Add Cache-Control to private (max-age=604800) to the headers of our image API calls. Will enable images to be cached in the Electron client, significantly enhancing performance for remote nodes.

**Importance**
:star2: :star2: :star2:

**Comment by rmisio** [comment]
@cpacia Hey Chris, as I explained in our IM chat, the cache header alone isn't going to do too much. You also need to include the additional workflow (etag or lastmodified headers, plus return 304 if if-modified-since of if-none-match headers come on subsequent requests). I'll just paste in what I IM'd:

=========

Anyhow, this is a pretty standard approach to this situation. The browser is really good at caching static assets, it just needs some direction (in the form of HTTP headers) from the server. First, when you send back a response from the get_image endpoint, be sure to include a `cache-control` header and set the `max-age` to something really, really high (many years). Don’t worry, the browser is still going to check with the server to see if a more recent asset is available (explained in more detail below). Also, include either a `Last-Modified` or `ETag` header. I don’t think the value of either really matters for our set-up.

With the above headers in place, after the first time the client requests an image from the server, on subsequent requests it will include one of two headers (`If-Modified-Since` or `If-None-Match`) with the request. The presence of these headers indicate to the server that the client has a cached copy of the resource and the client needs confirmation from the server on whether it should indeed use the cached resource or, if a newer version is available, the server would send back the newer version. Furthermore, the data contained within these headers allow the server to determine which version of the resource the client has, so it could know whether it has a newer one.

However… in our case, it’s a much simpler workflow. Since every time an image is changed, it gets a new hash and since the hash the client requests is coming from the server, you know that if a client is making a request with a cached asset, it is indeed the most recent. That leaves our workflow for the endpoint as follows:

```if has header If-Modified-Since or If-None-Match:
    return 304
else return asset
```

Returning 304 indicates to the client to go ahead and use the cached resource. Of course, for the server to return 304, it’s an incredibly inexpensive response… no network sweep is needed, no need to access the file system, no need to check the DB, no bulky image is being sent over the wire (be it P2P or HTTP). And, this image is going to be cached by the client for a really long time - until the client clears there cache.

=========

**Comment by drwasho** [comment]
Very kickass!
