### ISSUE TITLE
API call to determine if GUID generation is in progress

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#72]
When the client starts up, it needs to be able to call the server to find out if the GUID is being generated or already exists without calling the profile API.

**Comment by cpacia** [comment]
I'm thinking it would probably be best to do a websocket call. That way I can just push a notification over it when it's done. 

Would that make sense?

If you can connect to the websocket, then it's generating the guid. 
push notification comes over when it's done.

**Comment by hoffmabc** [comment]
We need to be able to tell if server is down and GUID generation.

**Comment by jjeffryes** [comment]
So:

1. websocket works, profile doesn't - probably generating a GUID
2. websocket fails - server is unreachable

Correct?

**Comment by cpacia** [comment]
Well. That depend.

If I used the same websocket port for the guid message, I may need to close the connect and reopen it in order to change the protocol that is run on that port. I don't know what that would do to your end. Would it close the connection? If not, I would probably use that. 

The other alternative would be to use a different port. But I would probably only open that if it's generating the guid, and leave it closed if it's not.
